name: AI Review

on:
  pull_request:
  issue_comment:
    types: [created]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' ||
      (github.event.issue.pull_request && startsWith(github.event.comment.body, '/ai-review-flex'))
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: prebuild
        run: pnpm install --frozen-lockfile

      - name: Build
        run: cd packages/ai-review-flex && pnpm build

      - name: AI Review
        run: node packages/ai-review-flex/dist/index.js
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LANGUAGE: Japanese
          CODING_GUIDE_PATH: ExampleOfCodigRules.md
          # CODING_GUIDE_READER: packages/ai-review-flex/dist/ci/codingGuide.js
          DEBUG: true
